name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nikhilmathure/docker-git-task2:latest
    - name: push docker image
      run: docker login -u nikhilmathure -p ${{ secrets.DOCKER_TOKEN }} && docker push nikhilmathure/docker-git-task2:latest
